# Generated by Django 4.0.4 on 2022-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('CourseNum', models.IntegerField(default='')),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=30)),
                ('Duration', models.TimeField(default='', max_length='')),
            ],
        ),
    ]
